# Generated by Django 5.0.6 on 2024-05-24 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_es_activo_usuario_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
