# Generated by Django 5.0.6 on 2024-06-02 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0002_remove_vehiculo_id_vehiculo_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='anio',
            field=models.IntegerField(max_length=4, null=True),
        ),
    ]
