# Generated by Django 5.0.6 on 2024-05-24 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estacion',
            name='latitud',
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='longitud',
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
    ]
