# Generated by Django 5.0.6 on 2024-05-24 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estaciones', '0002_alter_estacion_latitud_alter_estacion_longitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estacion',
            name='latitud',
            field=models.CharField(max_length=12, verbose_name='Latitud'),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='longitud',
            field=models.CharField(max_length=12, verbose_name='Longitud'),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='nombre',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='npuntoscarga',
            field=models.SmallIntegerField(),
        ),
    ]
