# Generated by Django 5.0.6 on 2024-05-28 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estaciones', '0003_alter_estacion_latitud_alter_estacion_longitud_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estacion',
            name='latitud',
            field=models.CharField(max_length=20, verbose_name='Latitud'),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='longitud',
            field=models.CharField(max_length=20, verbose_name='Longitud'),
        ),
    ]
