# Generated by Django 5.0.6 on 2024-06-09 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estaciones', '0004_alter_estacion_latitud_alter_estacion_longitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estacion',
            name='nombre',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
