# Generated by Django 5.0.6 on 2024-06-06 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valoraciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='valoracion',
            name='fecha',
            field=models.DateTimeField(null=True),
        ),
    ]
